#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+options: num:nil p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Имя дитя десяти лун от роду
#+date: <2023-12-01 Fri>
#+author: Horhik
#+email: horhik@nixos
#+language: ru
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6.11)
#+cite_export:

2. Имя дитя десяти лун от роду

Для прожившего 10 лун мальчика, который был рожден  =L!ax.L!alIdzemga= и имел свое старое имя. Как только он достиг истинного возраста (десять лун от роду), =L!aqolaas=, отец его, созвал все =Kwag'ul= племена в свой дом, и двое мужчин, что приглашали, гласили "Мы прибыли что бы позвать вас помочь окрасить того единственного, кому десять лун от роду". Так они сказали у дверей домов племен =Kwag'ul=. И когда все мужчины пришли, и мужчины помоложе, и дети тоже, они попросили женщину, чье имя =Aomol=, родом из =numaym Haanalino= из =O!omoyaэye=,  сжечь волосы на голове мальчика, которому десять лун от роду, привилегия ее была в этом, сжечь волосы мальчика, что десяти лун от роду. Тогда позвали других. Одну девушку, что бы она обписала дитя охрой, и двоих, даны им были эти роли, надеть на ноги и руки кольца. И звали двух эих девушек Единственные-Надевающие-на-Ноги-и-Руки-Кольца, и так, что поджигала волосы на голове дитя, нарекалась именем Поджигательнца-Десяти-Лун-Отроду-Дитя.

Как только сели, в тыльной части комнаты, девушки, где сидела =L!ax.L!alIdzemga=, мать дитя, десяти лун от роду, =Aomol= взяла ее гребень из тисового дерева, потому что пришла она со своим гребнем из тисового дерева и хорошо расколотой кедровой деревяшкой. И названия кедрового дерева, средства сжигания волос мальчику десяти лун отроду. Тогда =Aomol= попросила =L!ax.L!alIdzemga= положить дитя на свой живот и колени. Тогда =Aomol= причисала тисовым гребешком голову дитя, так что бы каждый волос его встал дыбом. И когда все волосы встали дыбом, тогда она тоже разломила кусочек кедра и подожгла его. И когда он загорелся она орудовала своей левой рукой тисовым гребешком и прикладывала его зубцы ближе к коже по правую сторону головы дитя, и тогда волосы дитя поднимались к гребешку. И тогда =Aomol=  сжигала их и конец был не далеко. А когда =Aomol= закончила выжигать волосы, она взяла блюдо и окунуло его в холодную воду из умывальника. Тогда она взяла щипцы и подняла небольшие расколенные камни и положила их в умывальник для дитя десяти лун от роду. Она положила четыре камня в воду, в этот умывальник. Как только =Aomol= закончила, она взяла дитя в свои руки и положила его на спину. И четыре раза окунула свою правую руку в слегка теплую воду, и четыре раза приложила свои влажные руки к голове дитя, и, в заключение, помыла его голову. Когда она завершила, помыла и тело его. После =Aomol= взяла измельченную кору кедра и обмазала ею дитя. На этом работа =Aomol= была завершена. И это ее обязанность, начиная с ее семейной истории.

Потом две девушки берут дитя из рук =Aomol= и надевают ремни на дитя, обладающего своим старым именем. И когда девушки надели ремни на ноги и руки дитя, женщина-художник забрала у них дитя и положила его на свои калени. Она попросила всех мужчин, и молодых мужчин, и всех детей выйти и рисовать на себе охрой. Сказав это она окрасила голову дитя и его лицо.

Закончив и дождавшись когда все мужчины себя обрисуют, девушка, которая надевает платок на голову, берет его из рук женщины-художника. Она единственная, кто клала расщипленную ламинарию у головы дитя, когда он только рождался. Она надевает платок на его голову. Когда она закончила, появляется =L!aqolaas=, отец. Он произносит и говорит: "О, племя, теперь завершена работа этих женщин, тех чья была привелегия по совершению данного для моего дитя имевшего старое имя. Теперь его имя изменено. Теперь вы перестаните называть его старым именем, теперь его имя =Wawalk.in=. Теперь его имя будет =Wawalk.in=, при рождении его имя было =Fort Rupert=". После он снимает платок и дает его всем мужчинам и детям. Теперь его имя девяти месяцев - =Wawalk.in=. Теперь завершены его два имени


