
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Hitchhiking stories
#+date: <2023-08-15 Tue>
#+author: Horhik
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6)
#+cite_export:
* Yesterday I got a driver and erased all data on his phone ;)

Listen to a little story. I had hitchhiked from Saint-Petersburg to Moscow. When about a hundred kilometers left, penultimate driver delivered me to the Kleen city and that was after the sunshine, rose-orange clouds, bus stops, lots of cars driving away in a high speed. Evening made me decide to start an "active hitchhiking" instead of trying to live the city and trying to catch someone from highway, staying somewhere in the nothingness and trees and the road only. I found closest filling station and started to pester each driver I saw.
There was two Uzbeks in the first car, I asked them are they going to moscow, but got no answer, guy driver I thought was under weed or just very gloopy, silence was an answer. I asked directly "could you give me a ride to Moscow", they nodded. After I tried to understand where can I leave my backpack. Silence. I pointed to a trailer behind a truck and they nodded. That was strange and a bit terrifying for me, so I let them off and continued my pestering session.

I talked to about 10 or more drivers, but no one wanted to give me a ride, sometimes I come back to highway and tried to catch someone, but no success. Once a security guard, who walked back and forth across the gas station came to me and told what there was one more car behind the building I stand close to.

I saw this truck and knocked to the right door. Driver saw me and opened it. He told me what going to Moscow and can take me, and standing here because his phone don't work, and he don't know where directly he have to ride. I sat, gave him my phone and we ride off.

FUCK XIAOMI, that's the point. There's was something weird with this phone, so it's just stukking at the booting stage. Obviously it was locked and had a very poor recovery. I didn't have a laptop in my backpack, so I could only erase all data, reboot to save mode and use this weird "mi connection" or something like what feature from this nasty corporation. We driving on my navigator, and about a half of the way I tried to make phone booting without selecting to erase all data, because driver have some job documents and all contacts there. Nothing happend.

Cuando me and a driver despaired in this piece of xiaomi, he allowed me to select erase option and, fortunately, it turned on and booted in.

FUCK GOOGLE, but obviously it helped. Greedy data collection is greedy data collection, but sometimes it really could help. Setting up the phone and connecting him to all accounts we restored necessary part of data to him be able to continue his job and make call wife (weird but initially her number wasn't saved in sim-card).

I was really happy what I could help a driver and he took me to Moscow.
More shortly, I though, that story sound like "I catch a driver, erased all data on his phone and got a ride to the location I wanted", brutally :)

